version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: heimdall
      APP_PORT: 80
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    volumes:
      - ${APP_DATA_DIR}/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    restart: unless-stopped